### ISSUE TITLE
Design changes

### ISSUE THREAD

**Issue by lakshyabatman** [dsc-jiit-128/issue-tracker#1]
Hola,
This project's design needs some work.
**How to solve**
- Change in CSS file
- **Do not change the class name as some of them is used by js scripts**

**HAPPY CODING**

**Comment by Thilagavathi1** [comment]
may i help on this.

**Comment by Thilagavathi1** [comment]
@lakshyabatman Have submitted PR[
fd6c466](https://github.com/dsc-jiit-128/issue-tracker/pull/7/commits/fd6c4664cb4b2d473ae23b236b2eccadd2a69670).please check this.

**Comment by michelleswalstra** [comment]
@lakshyabatman I would also like to give this a shot.

**Comment by michelleswalstra** [comment]
@lakshyabatman Added PR [here](https://github.com/dsc-jiit-128/issue-tracker/pull/10)

**Comment by lakshyabatman** [comment]
Ok, I'll have a look on it :D

**Comment by lakshyabatman** [comment]
@michelleswalstra , please resolve coflicts so I can merge your PR.
